/**
 * Local filesystem storage abstraction.
 *
 * Every other module (upload parser, ffprobe/ffmpeg services, streaming
 * controller) talks to storage ONLY through this file's functions -- never
 * through raw `fs` calls against a path it built itself, and DB rows never
 * store absolute filesystem paths, only "storage keys" (POSIX-style relative
 * paths under MEDIA_STORAGE_ROOT).
 *
 * This is intentionally shaped so that swapping local disk for an
 * S3-compatible object store later means replacing this one file: callers
 * only ever deal with storage keys + streams, never `path.join` or `fs`
 * directly.
 *
 * Layout (all paths are storage keys, relative to STORAGE_ROOT):
 *   <assetId>/original<ext>
 *   <assetId>/proxy.mp4
 *   <assetId>/thumbnail.jpg
 *   <assetId>/waveform.json
 *
 * Keeping every derived asset for a given media asset under one
 * `<assetId>/` directory means deleting a media asset is a single recursive
 * directory removal.
 */

const fs = require("fs");
const fsp = fs.promises;
const path = require("path");
const { STORAGE_ROOT } = require("../config/media");

/**
 * Resolve a storage key to an absolute filesystem path, refusing to leave
 * STORAGE_ROOT (path-traversal protection). Storage keys are always
 * generated by this module (never taken verbatim from user input), but this
 * check is a hard backstop regardless.
 */
function resolveAbsolutePath(storageKey) {
  if (typeof storageKey !== "string" || storageKey.length === 0) {
    throw new Error("storageKey must be a non-empty string");
  }

  const absolute = path.resolve(STORAGE_ROOT, storageKey);
  const rootWithSep = STORAGE_ROOT.endsWith(path.sep)
    ? STORAGE_ROOT
    : STORAGE_ROOT + path.sep;

  if (absolute !== STORAGE_ROOT && !absolute.startsWith(rootWithSep)) {
    throw new Error("Resolved storage path escapes storage root");
  }

  return absolute;
}

function assetDirKey(assetId) {
  return assetId;
}

function originalKey(assetId, extension) {
  const safeExt = extension.startsWith(".") ? extension : `.${extension}`;
  return path.posix.join(assetDirKey(assetId), `original${safeExt}`);
}

function derivedKey(assetId, kind) {
  const filenames = {
    proxy: "proxy.mp4",
    thumbnail: "thumbnail.jpg",
    waveform: "waveform.json",
  };
  const filename = filenames[kind];
  if (!filename) {
    throw new Error(`Unknown derived asset kind: ${kind}`);
  }
  return path.posix.join(assetDirKey(assetId), filename);
}

async function ensureParentDir(absolutePath) {
  await fsp.mkdir(path.dirname(absolutePath), { recursive: true });
}

/**
 * Pipe a readable stream into storage at `storageKey`. Resolves with bytes
 * written. If `maxBytes` is given and the stream exceeds it, the partial
 * file is removed and the promise rejects with an Error tagged
 * `err.code === "MAX_BYTES_EXCEEDED"`.
 */
function saveStream(storageKey, readableStream, maxBytes) {
  const absolutePath = resolveAbsolutePath(storageKey);

  return new Promise((resolve, reject) => {
    ensureParentDir(absolutePath)
      .then(() => {
        const writeStream = fs.createWriteStream(absolutePath);
        let bytesWritten = 0;
        let aborted = false;

        readableStream.on("data", (chunk) => {
          bytesWritten += chunk.length;
          if (typeof maxBytes === "number" && bytesWritten > maxBytes && !aborted) {
            aborted = true;
            const err = new Error(`Stream exceeded maxBytes (${maxBytes})`);
            err.code = "MAX_BYTES_EXCEEDED";
            readableStream.unpipe(writeStream);
            readableStream.destroy();
            writeStream.destroy();
            fsp.unlink(absolutePath).catch(() => {});
            reject(err);
          }
        });

        readableStream.on("error", (err) => {
          if (aborted) return;
          writeStream.destroy();
          fsp.unlink(absolutePath).catch(() => {});
          reject(err);
        });

        writeStream.on("error", (err) => {
          if (aborted) return;
          fsp.unlink(absolutePath).catch(() => {});
          reject(err);
        });

        writeStream.on("finish", () => {
          if (!aborted) resolve({ bytesWritten, absolutePath });
        });

        readableStream.pipe(writeStream);
      })
      .catch(reject);
  });
}

function createReadStream(storageKey, options) {
  const absolutePath = resolveAbsolutePath(storageKey);
  return fs.createReadStream(absolutePath, options);
}

async function exists(storageKey) {
  try {
    await fsp.access(resolveAbsolutePath(storageKey));
    return true;
  } catch {
    return false;
  }
}

async function stat(storageKey) {
  return fsp.stat(resolveAbsolutePath(storageKey));
}

/** Remove the entire directory for a media asset (original + all derived assets). */
async function deleteAssetDirectory(assetId) {
  const absolutePath = resolveAbsolutePath(assetDirKey(assetId));
  await fsp.rm(absolutePath, { recursive: true, force: true });
}

module.exports = {
  STORAGE_ROOT,
  resolveAbsolutePath,
  originalKey,
  derivedKey,
  saveStream,
  createReadStream,
  exists,
  stat,
  deleteAssetDirectory,
};
